const STORAGE_KEY="household-ledger-v1";
const fixedExpenses=[["삼성생명보험 · 희윤 실비",44818,"민정 2115 · 자동이체"],["코웨이 정수기",25900,"민정 2115 · 자동이체"],["현대해상보험 · 민정 실비",76630,"민정 2115 · 자동이체"],["DB손해보험 · 민정 운전자",10290,"민정 2115 · 자동이체"],["DB손해보험 · 민정 치과",27320,"민정 2115 · 자동이체"],["DB손해보험 · 희윤 치과",37490,"민정 2115 · 자동이체"],["LG유플러스 · 민정폰",104020,"민정 2115 · 자동이체"],["LG유플러스 · 희윤폰",29000,"민정 2115 · 자동이체"],["하나캐피탈 · 카니발 리스",739970,"민정 2115 · 자동이체"],["관사 관리비",265470,"민정 2115 · 자동이체"],["GS 도시가스",40090,"민정 2115 · 직접납부 / 변동"],["희윤 구몬",83000,"민정 2115 · 자동이체"],["DB손해보험 · 남편 운전자",10400,"남편 고정비 통장"],["신용위원회 대출",140000,"남편 고정비 통장"],["삼성생명보험 · 태평 실비",10083,"남편 고정비 통장"],["현대해상보험 · 세훈 실비",51040,"남편 고정비 통장"],["LG유플러스 · 인터넷",25000,"남편 고정비 통장"],["LG유플러스 · 세훈폰",40380,"남편 고정비 통장"],["개인회생",2044000,"월급통장 · 고정"]];
const seed=[{id:crypto.randomUUID(),type:"income",date:"2026-09-10",amount:5889900,merchant:"재정단 급여",category:"급여",person:"남편",account:"월급통장",memo:"9월 월급",receipt:null},{id:crypto.randomUUID(),type:"expense",date:"2026-09-10",amount:600000,merchant:"십일조",category:"교회/헌금",person:"남편",account:"월급통장",memo:"매달 변동",receipt:null},{id:crypto.randomUUID(),type:"expense",date:"2026-09-10",amount:1022000,merchant:"개인회생 1",category:"개인회생/채무",person:"남편",account:"월급통장",memo:"고정",receipt:null},{id:crypto.randomUUID(),type:"expense",date:"2026-09-10",amount:1022000,merchant:"개인회생 2",category:"개인회생/채무",person:"남편",account:"월급통장",memo:"고정",receipt:null},{id:crypto.randomUUID(),type:"transfer",date:"2026-09-10",amount:2700000,merchant:"민정 7777로 이체",category:"계좌이동",person:"민정",account:"월급통장",memo:"생활비 + 고정비 준비",receipt:null},{id:crypto.randomUUID(),type:"transfer",date:"2026-09-10",amount:300000,merchant:"남편 고정비 통장으로 이체",category:"계좌이동",person:"남편",account:"월급통장",memo:"고정비 준비",receipt:null},{id:crypto.randomUUID(),type:"expense",date:"2026-09-10",amount:9100,merchant:"쿠팡 누룽지팝 4개",category:"식비/간식",person:"남편",account:"카드/기타",memo:"",receipt:null}];
let transactions=load(); const won=n=>new Intl.NumberFormat("ko-KR").format(n)+"원";
function load(){try{const raw=localStorage.getItem(STORAGE_KEY);return raw?JSON.parse(raw):seed}catch{return seed}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(transactions))}
function calc(){const income=transactions.filter(x=>x.type==="income").reduce((s,x)=>s+x.amount,0),expense=transactions.filter(x=>x.type==="expense").reduce((s,x)=>s+x.amount,0),transfer=transactions.filter(x=>x.type==="transfer").reduce((s,x)=>s+x.amount,0);incomeTotal.textContent=won(income);expenseTotal.textContent=won(expense);transferTotal.textContent=won(transfer);balanceTotal.textContent=won(income-expense)}
function renderFixed(){fixedExpensesEl.innerHTML=fixedExpenses.map(([name,amount,note])=>`<div class="fixed-item"><div><strong>${name}</strong><small>${note}</small></div><strong>${won(amount)}</strong></div>`).join("");fixedTotal.textContent=won(fixedExpenses.reduce((s,x)=>s+x[1],0))}
function renderCategories(){const grouped={};transactions.filter(x=>x.type==="expense").forEach(x=>grouped[x.category]=(grouped[x.category]||0)+x.amount);const entries=Object.entries(grouped).sort((a,b)=>b[1]-a[1]),max=entries[0]?.[1]||1;categoryBars.innerHTML=entries.map(([cat,amount])=>`<div><div class="bar-head"><span>${cat}</span><strong>${won(amount)}</strong></div><div class="bar-track"><div class="bar-fill" style="width:${Math.max(4,amount/max*100)}%"></div></div></div>`).join("")||"<p class='sub'>아직 지출 기록이 없어요.</p>"}
function iconFor(x){if(x.type==="income")return"💰";if(x.type==="transfer")return"↔️";return({"식비/간식":"🥨","교회/헌금":"⛪","개인회생/채무":"💳","보험":"🛡️","통신":"📱","차량":"🚙","교육":"📚","주거/공과금":"🏠"}[x.category]||"🧾")}
function renderTransactions(){const pf=personFilter.value,tf=typeFilter.value;const list=[...transactions].filter(x=>pf==="all"||x.person===pf).filter(x=>tf==="all"||x.type===tf).sort((a,b)=>(b.date+b.id).localeCompare(a.date+a.id));transactionsEl.innerHTML=list.map(x=>`<div class="tx"><div class="tx-icon">${iconFor(x)}</div><div class="tx-main"><strong>${x.merchant}</strong><small>${x.date} · ${x.category} · ${x.person} · ${x.account}${x.memo?" · "+x.memo:""}</small></div><div class="tx-amount ${x.type}">${x.type==="expense"?"-":x.type==="income"?"+":"↔ "}${won(x.amount)}</div><div class="tx-actions">${x.receipt?`<button class="icon-btn" data-receipt="${x.id}">📷</button>`:""}<button class="icon-btn" data-delete="${x.id}">삭제</button></div></div>`).join("")||"<p class='sub'>조건에 맞는 기록이 없어요.</p>";document.querySelectorAll("[data-delete]").forEach(btn=>btn.onclick=()=>{if(confirm("이 기록을 삭제할까요?")){transactions=transactions.filter(x=>x.id!==btn.dataset.delete);save();render()}});document.querySelectorAll("[data-receipt]").forEach(btn=>btn.onclick=()=>{const tx=transactions.find(x=>x.id===btn.dataset.receipt);if(tx?.receipt){receiptPreview.src=tx.receipt;receiptDialog.showModal()}})}
function render(){calc();renderFixed();renderCategories();renderTransactions()}
const incomeTotal=document.querySelector("#incomeTotal"),expenseTotal=document.querySelector("#expenseTotal"),transferTotal=document.querySelector("#transferTotal"),balanceTotal=document.querySelector("#balanceTotal"),fixedExpensesEl=document.querySelector("#fixedExpenses"),fixedTotal=document.querySelector("#fixedTotal"),categoryBars=document.querySelector("#categoryBars"),transactionsEl=document.querySelector("#transactions"),personFilter=document.querySelector("#personFilter"),typeFilter=document.querySelector("#typeFilter"),receiptDialog=document.querySelector("#receiptDialog"),receiptPreview=document.querySelector("#receiptPreview");
document.querySelector("#date").value="2026-09-10";
document.querySelector("#entryForm").addEventListener("submit",async e=>{e.preventDefault();const file=document.querySelector("#receipt").files[0];let receipt=null;if(file){if(file.size>1500000){alert("1차 버전에서는 1.5MB 이하 이미지를 권장해요.");return}receipt=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}transactions.push({id:crypto.randomUUID(),type:type.value,date:date.value,amount:Number(amount.value),merchant:merchant.value.trim(),category:type.value==="transfer"?"계좌이동":category.value,person:person.value,account:account.value,memo:memo.value.trim(),receipt});save();e.target.reset();document.querySelector("#date").value="2026-09-10";render()});
personFilter.onchange=renderTransactions;typeFilter.onchange=renderTransactions;document.querySelector("#closeDialog").onclick=()=>receiptDialog.close();document.querySelector("#resetBtn").onclick=()=>{if(confirm("입력한 내용을 모두 지우고 처음 상태로 돌아갈까요?")){transactions=JSON.parse(JSON.stringify(seed));save();render()}};render();
